<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure to delete this item?' => 'Вы уверены, что хотите удалить?',
  'Delete' => 'Удалить',
  'Displaying {start}-{end} of {count} result(s).' => 'Показано {start}-{end} из {count}',
  'Either "name" or "value" must be specified for CDataColumn.' => '',
  'No results found.' => 'Ничего не найдено',
  'Not set' => 'Не задано',
  'Please specify the "attributes" property.' => '',
  'Please specify the "model" property.' => '',
  'Sort by: ' => 'Сортировать по:',
  'The "dataProvider" property cannot be empty.' => '',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '',
  'The property "itemView" cannot be empty.' => '',
  'Total {count} result(s).' => 'Всего {count}.',
  'Update' => 'Изменить',
  'View' => 'Просмотреть',
  '{class} must specify "model" and "attribute" or "name" property values.' => '',
);
